import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
    ClerkProvider
} from '@clerk/nextjs'
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import TopNav from "@/components/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
              <div className={"h-screen flex flex-col justify-between"}>
                  <div>
                    <TopNav/>
                  </div>
                  <div className={"flex-1"}>
                    {children}
                  </div>
                  <div>
                    <BottomNav/>
                  </div>
              </div>
          </body>
        </html>
      </ClerkProvider>
  );
}
